### ISSUE TITLE
Decimal number cannot start with zero

### ISSUE THREAD

**Issue by SaitoAtsushi** [s-expressions/pose#19]
The current specification does not allow the example.

```
0.123
```

```
number       = '0' | decimal
decimal      = minus? onenine digit* fraction? exponent?
```

Which is wrong, the spec or the example?

**Comment by lassik** [comment]
The spec is wrong. Thank you for catching the mistake.

**Comment by lassik** [comment]
POSE is supposed to have the same number syntax as JSON, IIRC:
